[package]
name = "libafl_nautilus_fuzzer"
version = "0.2.0"
authors = [
    "Andrea Fioraldi <andreafioraldi@gmail.com>",
    "Dominik Maier <domenukk@gmail.com>",
]
edition = "2021"

[features]
default = ["std"]
std = []

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
which = { version = "4.3" }
num_cpus = "1.0"

[dependencies]
libafl = { version = "0.15.3", features = ["default", "nautilus"] }
libafl_targets = { version = "0.15.3", features = [
    "sancov_pcguard_hitcounts",
    "libfuzzer",
] }
libafl_bolts = "0.15.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
# TODO Include it only when building cc
libafl_cc = { version = "0.15.3" }
libafl-fandango-pyo3 = { git = "https://github.com/riesentoaster/libafl-fandango-pyo3" }
clap = { version = "4.0", features = ["derive"] }

[lib]
name = "libafl_nautilus_fuzzer"
crate-type = ["staticlib"]
